# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

# hostname: "" # MESSENGER_HOST

# applicationID: "" # MESSENGER_APP_ID
# accessToken: "" # MESSENGER_ACCESS_TOKEN
# appSecret: "" # MESSENGER_APP_SECRET

# verifyToken: "" # MESSENGER_VERIFY_TOKEN

# displayGetStarted: true
# greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
persistentMenuItems: [
      {
        "title":"Menu com submenus",
        "type":"nested",
        "call_to_actions":[ {
          "type":"postback",
          "title":"Sub-Opcao 1",
          "payload":"nao interessa o q tem aqui"
        }, {
          "type":"postback",
          "title":"Sub-Opcao 2",
          "payload":"nao pode estar vazio"
        }
        ]   
      },
      {
        "title":"Opcao 1",
        "payload":"coloca algo",
        "type":"postback"
      }, {
        "type":"web_url",
        "url":"https://github.com/NIAEFEUP/chatbot-sigarra",
        "webview_height_ratio":"tall",
        "title":"Github repo"
      }
]
 
targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true
